services:
  - docker

language: python
python: "3.6"

jobs:
  include:
    - stage: test
      script: python -m pytest -v
    - stage: deploy
      script:
        - test $TRAVIS_BRANCH = "master" &&
          sh .travis/deploy_dockerhub.sh &&
          sh .travis/deploy_heroku.sh
