sudo: required

services:
  - docker

language: python
python:
  - "2.7"
  - "3.4"
script:
  - python -m pytest -v
  - pwd
  - ls
  - whoami

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
